# SPDX-FileCopyrightText: 2022 James R. Barlow
# SPDX-License-Identifier: MPL-2.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
        exclude: \.rst$
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
        args: ["--pytest-test-first"]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.6
    hooks:
      - id: clang-format
        files: "src/.*\\.(cpp|h|hpp)?$"
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.287"
    hooks:
      - id: ruff
        files: "src/.*\\.pyi?$"
  - repo: https://github.com/psf/black
    rev: 23.9.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies:
          - lxml-stubs
          - types-Pillow
          - types-requests
          - types-setuptools
